---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: bankingfinance
          image: radhikaps/bankingproject:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: banking
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: banking
